### ISSUE TITLE
Check-ins app loads a purple page

### ISSUE THREAD

**Issue by cstout1** [seven1m/rpi-check-in-printer#3]
This morning, we were unable to print using the RPI station as the check ins app on rpi was not fully loading. Not sure if a dependency changed on PCO's side, but restarting and reloading the app results in the same experience. CUPS test print works. VNC works. No PI system updates have applied (they are disabled). Not sure where else to check. The printer status page in the check-ins app loads a white page with the PCO logo at the bottom - not usable.

![Screenshot 2024-09-15 at 10 13 05 AM](https://github.com/user-attachments/assets/c6f058c6-025a-40ef-863f-705795dbf18a)

**Comment by seven1m** [comment]
Same thing happened on my systems as well. Honestly I don't know if I will be able to fix it. But I will try.

**Comment by passtpro** [comment]
Same here. Did Planning Center pull support for Linux Distros? I honestly can't remember if they had an official Linux build or not.

**Comment by seven1m** [comment]
Planning Center never supported Linux. I will see if I can compile a newer version of the Electron app for Linux...

**Comment by seven1m** [comment]
There is a newer version of the Check-Ins app that should fix this: https://check-ins-printing.s3.amazonaws.com/planning-center-check-ins-1.11.0-armv7l.zip

You'll need to download and unzip this into the folder on your Pi at `/home/pi/planning-center-check-ins` and then reboot.

**Comment by cstout1** [comment]
Thank you for creating the update. I'm unable to download, however. Reaching an access denied page:
```<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B240WMZAWHV103R6</RequestId>
<HostId>f+h1NXuFDmEk4lDkixUya9LVriSQcKBcRZI8RaB26DZ0rn6Qkphve7c0qQKMONMOZcb8t6egB+7hvGn951JF6CjOanJsD6s2X4qjYrxhn90=</HostId>
</Error>```

**Comment by seven1m** [comment]
OK let me see about fixing that!

**Comment by seven1m** [comment]
OK, try again!

**Comment by cstout1** [comment]
😅 74 labels waiting to print. It's so nice not to see a big purple window. Thank you!

So, what was the problem and is there anything I could have done differently on my end?

**Comment by seven1m** [comment]
If I'm ever not around (bus factor), then this could be useful for someone else trying to get a Linux version of the Check-Ins Electron app: https://github.com/seven1m/rpi-check-in-printer/blob/master/doc/compiling-check-ins-for-linux.md

**Comment by cstout1** [comment]
Praying for no bus. Thank you for all your hard work on this. It's very appreciated.
